### PR TITLE
Fix deletion bug

### LINKED ISSUE #241: Deletion of steward-pipelinerun does not update status nor result
If a steward-pipelinerun is deleted the `state` and the `result` are not updated.

[See here](https://github.com/SAP/stewardci-core/blob/master/pkg/runctl/controller.go#L270)

Expected behavior would be that `result` is set to [`ResultDeleted`](https://github.com/SAP/stewardci-core/blob/master/pkg/apis/steward/v1alpha1/run_types.go#L215)
and `state` is set to [`StateFinished`](https://github.com/SAP/stewardci-core/blob/master/pkg/apis/steward/v1alpha1/run_types.go#L193).

### PR DESCRIPTION
**Pull request by rinckm**
### Description

fixes #241 

### Submitter checklist

- [ ] Change has been tested (on a back-end cluster)
- [ ] (If applicable) Jira backlog item ID added to the PR title and the [changelog.yaml] entry
- [ ] [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change)
- [ ] Semantic version diffed against [last release][releases] and updated accordingly. In this project the version has to be maintained here:
    - [/charts/steward/Chart.yaml](https://github.com/SAP/stewardci-core/blob/master/charts/steward/Chart.yaml) (`version` and `appVersion`)

In case dependencies have been updated:
- [ ] Links to external changelogs, since the last release of our component, added to the [changelog.yaml] entry (description).
- [ ] Changelogs read thoroughly, potential impact described, upgrade notes prepared (if necessary)
- [ ] Check if dependency updates affect our semantic version increment.

### Reviewer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There is at least 1 approval for the pull request and no outstanding requests for change
- [ ] All voter checks have passed
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] The Pull Request title is understandable and reflects the changes well
- [ ] The Pull Request description is understandable and well documented
- [ ] [changelog.yaml] entry for this Pull Request has been added
    - [ ] Changelog entry contains all required information
    - [ ] 'Upgrade notes' are documented in changelog.yaml (if required)

[changelog.yaml]: https://github.com/SAP/stewardci-core/changelog.yaml
[releases]: https://github.com/SAP/stewardci-core/releases

### CODE REVIEW

File: pkg/runctl/controller.go [hunk 1]
```diff
@@ -265,13 +265,28 @@ func (c *Controller) syncHandler(key string) error {
 		return nil
 	}
 
+	// Finished and no deletion timestamp, no need to process anything further
```
Comment (jia-jerry) [inline pkg/runctl/controller.go:268]: It is really odd that we double check the state for 2nd time. See  fast exit part. The root cause should be you `Get real pipelineRun bypassing cache`. Would you tell me why shall we need to fetch the object again from API server?

File: changelog.yaml [hunk 2]
```diff
@@ -51,6 +51,13 @@
 - version: NEXT
   date: TBD
   changes:
+     - type: bug
+       impact: patch
+       title: Fix deletion bug #241
+       description: |-
+         When pipelinerun is deleted the state and the result is not updated. This is fixed now.
+       upgradeNotes: ResultDeleted was only used in the metrics before. Now it can also occur as a pipeline run result.
+       pullRequestNumber: <pull request number(s)>
```
Comment (rinckm) [inline changelog.yaml:60]:
```suggestion
       pullRequestNumber: 242
```

File: pkg/runctl/controller.go (hunk 1 above)
Comment (rinckm) [reply pkg/runctl/controller.go]: This is legacy coding I don't want to touch in this fix.

**Review by jia-jerry — APPROVED** [review]
looks good to me.

File: changelog.yaml [hunk 3]
```diff
@@ -51,6 +51,13 @@
 - version: NEXT
   date: TBD
   changes:
+     - type: bug
+       impact: patch
+       title: Fix deletion bug #241
+       description: |-
+         When pipelinerun is deleted the state and the result is not updated. This is fixed now.
+       upgradeNotes: ResultDeleted was only used in the metrics before. Now it can also occur as a pipeline run result.
```
Comment (alxsap) [inline changelog.yaml:59]:
```suggestion
       upgradeNotes: `ResultDeleted` was only used in the metrics before. Now it can also occur as a pipeline run result.
```

Comment (alxsap) [reply changelog.yaml:59]: Does the build-syncer need to be adapted?

Comment (alxsap) [reply changelog.yaml:59]: Are there (internal) components which need to be adapted?

File: changelog.yaml [hunk 4]
```diff
@@ -51,6 +51,13 @@
 - version: NEXT
   date: TBD
   changes:
+     - type: bug
+       impact: patch
+       title: Fix deletion bug #241
+       description: |-
+         When pipelinerun is deleted the state and the result is not updated. This is fixed now.
```
Comment (alxsap) [inline changelog.yaml:58]:
```suggestion
         When a pipeline run was deleted the state and the result has not been updated. This is fixed now.
```

File: pkg/runctl/controller.go [hunk 5]
```diff
@@ -265,13 +265,23 @@ func (c *Controller) syncHandler(key string) error {
...
+
 	// Check if object has deletion timestamp
 	// If not, try to add finalizer if missing
 	if pipelineRun.HasDeletionTimestamp() {
 		runManager := c.createRunManager(pipelineRun)
 		err = runManager.Cleanup(pipelineRun)
+
 		if err == nil {
-			err = pipelineRun.DeleteFinalizerIfExists()
+			pipelineRun.UpdateResult(api.ResultDeleted)
```
Comment (alxsap) [inline pkg/runctl/controller.go:283]: Where is the finalizer deleted now?

Comment (rinckm) [reply pkg/runctl/controller.go:283]: The `finish` function removes the finalizer.

Comment (alxsap) [reply pkg/runctl/controller.go:283]: OK, in `c.finish`.

**Review by alxsap — APPROVED** [review]
see comments

File: changelog.yaml [hunk 6]
```diff
@@ -51,6 +51,13 @@
 - version: NEXT
   date: TBD
   changes:
+     - type: bug
+       impact: patch
+       title: Fix deletion bug #241
+       description: |-
+         When a pipeline run was deleted the state and the result has not been updated. This is fixed now.
+       upgradeNotes: `ResultDeleted` was only used in the metrics before. Now it can also occur as a pipeline run result.
```
Comment (rinckm) [inline changelog.yaml:59]:
```suggestion
       upgradeNotes: |-
         `ResultDeleted` was only used in the metrics before. Now it can also occur as a pipeline run result.
```
