### PR TITLE
fix #59 - Missing resilience in run controller when updating service account

### LINKED ISSUE #59: Missing resilience in run controller when updating service account
Happened one time after creating a pipeline run. Was successful all the other times.
```yaml
history:
  - 'ERROR: error syncing resource (demok8s-bjsb2 - status:preparing): failed to update
    service account "default": Operation cannot be fulfilled on serviceaccounts "default":
    the object has been modified; please apply your changes to the latest version
    and try again'
  - 'ERROR: error deleting namespace (demok8s-bjsb2 - status:cleaning): error deleting
    namespace ''steward-run-ripx3yrn80i04ulh'': Operation cannot be fulfilled on namespaces
    "steward-run-ripx3yrn80i04ulh": The system is ensuring all content is removed
    from this namespace.  Upon completion, this namespace will automatically be purged
    by the system.'
```

### PR DESCRIPTION
**Pull request by anbrsap**

### CODE REVIEW

**Comment by anbrsap** [comment]
fixes #59

File: pkg/runctl/run_manager.go [hunk 1]
```diff
@@ -127,31 +127,46 @@ func (c *runManager) prepareRunNamespace(pipelineRun k8s.PipelineRun) error {
...
+				serviceAccount.AttachSecrets(pipelineCloneSecretName)
+			}
+			serviceAccount.AttachImagePullSecrets(imagePullSecrets...)
+			err = serviceAccount.Update()
+			if err == nil {
+				break // ...the retry loop
+			}
+			if !k8serrors.IsConflict(err) {
+				return errors.Wrapf(err, "failed to update service account %q", serviceAccountName)
+			}
```
Comment (alxsap) [inline pkg/runctl/run_manager.go]: A comment could make it more readable
```suggestion
			}
			// conflict - object changed, retrying again with the latest version
```

File: pkg/runctl/run_manager.go [hunk 2]
```diff
@@ -127,31 +127,46 @@ func (c *runManager) prepareRunNamespace(pipelineRun k8s.PipelineRun) error {
...
 		}
 	}
 
-	//Add Role Binding to Service Account
+	// grant role to service account
 	_, err = serviceAccount.AddRoleBinding(runClusterRoleName, runNamespace)
 	if err != nil {
-		return errors.Wrap(err, "failed to create role binding")
+		return errors.Wrapf(err, "failed to create role binding for service account %q", serviceAccountName)
```
Comment (alxsap) [inline pkg/runctl/run_manager.go]: In general, the `runNamespace` in logs would be helpful. Otherwise we only see:
`failed to create role binding for service account "default"` which is not very helpful

Comment (anbrsap) [reply pkg/runctl/run_manager.go]: Fixed by ee32ee5a.

File: pkg/runctl/run_manager.go (hunk 1 above)
Comment (anbrsap) [reply pkg/runctl/run_manager.go]: Fixed by ee32ee5a.
